# Generated by Django 5.0.6 on 2024-09-29 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donnation_box', '0002_donation_userregistration_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='approved_volunteer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_approved': True, 'user_type': 'Volunteer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donnation_box.userregistration'),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
