# Generated by Django 5.0.6 on 2024-10-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donnation_box', '0003_donation_approved_volunteer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='notification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
