# Generated by Django 5.0.6 on 2024-10-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donnation_box', '0004_userregistration_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Picked', 'Picked Up'), ('Approved', 'Approved')], default='Available', max_length=50),
        ),
    ]
