# Generated by Django 5.0.6 on 2024-10-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donnation_box', '0006_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='card_last_four',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
