# Generated by Django 5.0.6 on 2024-10-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donnation_box', '0007_paymenthistory_card_last_four'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='user_type',
            field=models.CharField(choices=[('user', 'user'), ('Volunteer', 'Volunteer'), ('Organization', 'Organization')], max_length=50),
        ),
    ]
